---
title: "Yi Lui Data Analysis: Transfer Efficiency"
author: "MFK"
date: "25/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
pacman::p_load(dplyr,brms,tidyr,ggplot2,lme4,lubridate)

```


# Fluorescent powder
This imports Yi lui's data and skim the columns using skimr

```{r Yi's data import}
dY<-vroom::vroom("../data/Yi.data.longformat.20191121_censoring_handled.csv") %>% janitor::clean_names()

# convert to UK date
dy<-dY %>% mutate(date=lubridate::mdy(date))
skimr::skim(dY)
```

# Plot the individual intensity/powder area vs contact number for all the surfaces


```{r rel intensity vs contact number and by date}
dY %>% 
  #filter(surface=="Plastic" ) %>% 
  #filter(id<21) %>% 
  ggplot()+
  geom_point(aes(x=contact_number,y=raw_int_d/(powder_area),colour=gloves),alpha=0.1)+
  geom_smooth(aes(x=contact_number,y=raw_int_d/(powder_area),colour=gloves),method="lm",se=FALSE)+
  scale_y_continuous(trans="log10",limits=c(3e4,4e5 ))+
  ylab("Intensity/Powder Area")+
  xlab("Contact number")+
  facet_wrap(~gloves+date)+
  scale_colour_brewer(palette = "Set1")+
  theme_bw()+
  labs(color = "Gloves")+
  #font_size(14)
  theme(text = element_text(size=14),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14))

```

#
```{r}

# Individual powder area vs contact number and loading weight 
dY %>% 
  filter(surface=="Plastic" ) %>% 
  filter(id<21) %>% 
  ggplot()+
  geom_point(aes(x=contact_number,y=raw_int_d/(powder_area),colour=gloves),size=5)+
  #geom_smooth(aes(x=contact_number,y=raw_int_d/(powder_area),colour=gloves),method="lm",se=FALSE)+
  scale_y_continuous(trans="log10",limits=c(3e4,4e5 ))+
  ylab("Intensity/Powder Area")+
  xlab("Contact number")+
  facet_wrap(~id)+
  scale_colour_brewer(palette = "Set1")+
  theme_bw()+
  labs(color = "Gloves")+
  #font_size(14)
  theme(text = element_text(size=14),
  axis.text.x=element_text(size=14),
  axis.text.y=element_text(size=14))->a

  ggsave(a,filename = "images/individual_relative_int_vs_contact_number.png",dpi=300, device="png",width = 15, height = 10, units = "in",bg="white")



# Raw int violin plots faceted by surface
dY %>% 
  # filter(surface=="Plastic" ) %>% 
  # group_by(surface,contact_number,gloves) %>% 
  # summarise(Mean=mean(powder_area),SD=sd(powder_area))
  ggplot()+
  geom_violin(aes(x=as.factor(contact_number),y=raw_int_d,fill=gloves),draw_quantiles = c(0.25,0.5,0.95))+
  scale_y_continuous(trans = "log10")+
  scale_fill_brewer(palette = "Set1")+
  facet_wrap(~surface,scales="free",nrow=3)+
  ylab("Raw intensity")+
  xlab("Contact number")+
  labs(fill = "Gloves")+
  hrbrthemes::theme_ipsum()

```

# Some investigative plots
```{r investigative plots}
#Plot log10(raw_int_d) vs contact_number for each ID and colour by gloves
dY%>%
filter(surface=="Plastic") %>%
filter(id>20 & id<=40) %>%
ggplot()+
geom_point(aes(x=contact_number,y=raw_int_d,colour=gloves),size=4)+
scale_colour_brewer(palette="Set1")+
scale_y_continuous(trans="log10")+
facet_wrap(~id)+
xlab("Contact number")+
ylab("Intensity units")+
theme_bw()+
labs(color='Gloves')+
theme(text = element_text(size=14),axis.text.x=element_text(size=14))  ->a

#save ggplot figure
# ggsave(a,"images/intensity_for_each_ID.png",device="png",units=c("cm"),width=30)
ggsave(a,filename = "images/intensity_for_each_ID_plastic_21_40.png",dpi=300, device="png",width = 10, height = 10, units = "in")


# Create a scatter plot of the intensity for each ID and colour by gloves, facet by surface

dY%>%
ggplot()+
geom_jitter(aes(x=contact_number,y=raw_int_d/powder_area,colour=date),size=4,alpha=0.4)+
scale_colour_brewer(palette="Set1")+
# geom_smooth(method="lm",se=TRUE,aes(x=contact_number,y=raw_int_d/powder_area,colour=gloves))+
facet_grid(gloves~surface)+
xlab("Contact number")+
ylab("Intensity units")+
scale_y_continuous(trans = "log10")+
theme_bw()+
labs(color='Date')+
theme(text = element_text(size=14),axis.text.x=element_text(size=14))  ->a

ggsave(a,filename = "images/aggregated_intensity.png",dpi=300, device="png",width = 12, height = 10, units = "in")




```

# LMER4 model fit
Here we fit a Linear Mixed Effects Model using LMER4 to the data.

```{r LMER4 raw_int_d }
#Here we fit a LMER4 model from LMER4 to the data, with raw_ind_d as the dependent variable
#We
model_fit_g<-lme4::lmer(log10(raw_int_d)~powder_area + contact_number + gloves + surface + (powder_area+contact_number+gloves+surface | id),
                  data = dY,
                  weights=log10(raw_int_d))
summary(model_fit_g)
plot(model_fit_g)

```


# BRMS model fit
Here we fit a Bayesian Regression Model using BRMS to the data.

```{r BRM raw_int_d }
#Here we fit a BRM model from BRSM to the data, with raw_ind_d as the dependent variable
#We 
model_fit_BRMS<-brms::brm(data = dY,raw_int_d~powder_area+contact_number+gloves+surface+(powder_area+contact_number+gloves+surface|id),
                       family = lognormal(link = "identity", link_sigma = "log"))
summary(model_fit_BRMS)
plot(model_fit_BRMS)

model_fit_BRMS

```

## Calculate Lambda

```{r calculate lambda}
# Extract the coefficients from the model summary
coefs <- summary(model_fit_BRMS)$coefficients

# Calculate the transfer efficiency using the coefficients for the predictors
lambda <- coefs['PowderArea'] / coefs['ContactNumber']

# Print the transfer efficiency
lambda

```


